markdown: kramdown
permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""

google_analytics_id: UA-45256157-1

repository: https://github.com/jekyll/jekyll
help_url: https://github.com/jekyll/jekyll-help
bbs: https://bbs.fcgvisa.com/

collections:
  docs:
    output: true
